### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by psifertex** [jmprdi/binja-division-deoptimization#1]
We're in the process of adding automatic dependency resolution and unfortunately we realized our `plugin.json` wasn't the best choice and are instead going to be using the python-standard `requirements.txt`. We've got a blog post coming soon with more details but if you want to make a requirements.txt and get a head start, that'd be great!

**Comment by psifertex** [comment]
Are you willing to accept a PR for this?

**Comment by psifertex** [comment]
Ping -- happy to submit a PR for this, just would need you to generate the release once done.

**Comment by nbanmp** [comment]
Sorry I totally haven't been paying any attention to this repo, if you still care/if this is still valuable, I'll generate the release.

**Comment by psifertex** [comment]
Honestly, given our recent improvements that do this out of the box i'm not sure it's necessary anymore. I'm inclined to just remove it from the plugin manager unless you want to update it as an example plugin and there may indeed still be some cases that z3 can solve that our default implementation cannot so either way, it's up to you.

**Comment by nbanmp** [comment]
Yup, let's just remove it from the manager. This being in product is just better. :)

**Comment by psifertex** [comment]
Done, thanks.
